version: '3.8'

services:
  app:
    build: .
    container_name: sistema_paqueteria
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: paqueteria_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  tests:
    build: .
    container_name: sistema_paqueteria_tests
    volumes:
      - .:/app
    command: pytest
    depends_on:
      - db

volumes:
  db_data:
